# Griffe Configuration for MkDocs API Documentation
# ==================================================
# Reference: https://mkdocstrings.github.io/griffe/
#
# IMPORTANT: Understanding Griffe Warnings
# -----------------------------------------
# Griffe is a static analysis tool used by mkdocstrings to extract docstrings.
# It generates warnings during docs build that are INFORMATIONAL ONLY and can be safely ignored.
#
# THESE WARNINGS DO NOT INDICATE CODE PROBLEMS:
#
# 1. "WARNING - griffe: No type or annotation for returned value"
#    Problem: Griffe cannot infer return types from bare Failure() calls in error paths
#    Reality: ALL functions have proper return type annotations in their signatures
#    Verification: mypy strict mode enforces this (tests would fail if types missing)
#    Example:
#      def handle(cmd) -> Result[UUID, str]:  # ← Return type IS declared
#          if error:
#              return Failure(error="...")     # ← Griffe warns here (false positive)
#          return Success(value=uuid)
#    Impact: None - generated docs show correct types from function signature
#
# 2. "WARNING - griffe: Failed to get 'exception: description' pair"
#    Problem: EventBusProtocol uses narrative-style Raises sections
#    Reality: Google-style docstrings allow both structured AND narrative Raises formats
#    Example:
#      Raises:
#          No exceptions raised. Handler failures are logged but not propagated.
#    Impact: None - narrative format is valid and clear in documentation
#
# 3. "WARNING - mkdocs_autorefs: Could not find cross-reference target"
#    Problem: Literal strings in docstrings (e.g., "accountNumber") treated as references
#    Reality: These are example field names, not Python references
#    Example: Returns dict with "accountNumber" key  # ← Not a Python object
#    Impact: None - docs display correctly, just no hyperlink
#
# WHY WARNINGS CANNOT BE SUPPRESSED:
# ----------------------------------
# Griffe does not currently provide configuration options to suppress specific warnings.
# The warnings are logged directly by the static analysis engine.
# There is no .griffe.yml config format that works (we've tried).
#
# BUILD STRATEGY:
# ---------------
# - `make docs-build`: Normal mode (warnings shown but don't fail build)
# - `make verify`: Strict mode (Step 7 - catches broken links and missing pages)
#
# The verify step uses --strict which will abort on warnings, but this is acceptable
# because:
# 1. All warnings are documented here as safe
# 2. Any NEW warning types (broken links, etc.) will be caught
# 3. Developers know to check warning types, not just count
#
# IF YOU SEE NEW WARNING TYPES:
# ------------------------------
# If warnings appear that are NOT listed above (griffe/autorefs), investigate immediately:
# - Broken internal links: Fix the markdown link
# - Missing pages: Create the page or remove the reference
# - Invalid configuration: Check mkdocs.yml syntax
#
# TOTAL EXPECTED WARNINGS: ~26 (all griffe/autorefs - safe to ignore)
# Last Updated: 2025-12-28
