"""add audit logs table

Revision ID: b7a1d68f632a
Revises: bb433187db3b
Create Date: 2025-11-15 23:03:12.590341+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7a1d68f632a"
down_revision: Union[str, Sequence[str], None] = "bb433187db3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column(
            "action",
            sa.String(length=100),
            nullable=False,
            comment="Audit action type (e.g., user_login, password_changed)",
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=True,
            comment="User who performed the action (None for system actions)",
        ),
        sa.Column(
            "resource_type",
            sa.String(length=100),
            nullable=False,
            comment="Type of resource affected (user, account, provider, etc.)",
        ),
        sa.Column(
            "resource_id",
            sa.Uuid(),
            nullable=True,
            comment="Specific resource identifier (if applicable)",
        ),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
            comment="Client IP address (required for authentication events)",
        ),
        sa.Column(
            "user_agent",
            sa.String(length=500),
            nullable=True,
            comment="Client user agent string",
        ),
        sa.Column(
            "context",
            sa.JSON(),
            nullable=False,
            comment="Additional event context (JSONB - extensible without schema changes)",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_audit_resource",
        "audit_logs",
        ["resource_type", "resource_id"],
        unique=False,
    )
    op.create_index(
        "idx_audit_user_action", "audit_logs", ["user_id", "action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_resource_id"), "audit_logs", ["resource_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_resource_type"),
        "audit_logs",
        ["resource_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    # ### end Alembic commands ###

    # CRITICAL: Enforce immutability with PostgreSQL RULES
    # These RULES block UPDATE and DELETE operations to ensure audit trail integrity
    # Required for PCI-DSS, SOC 2, and GDPR compliance
    #
    # KNOWN LIMITATION: TRUNCATE bypasses RULES
    # - Table owner (dashtam_user) can still TRUNCATE audit_logs
    # - REVOKE TRUNCATE doesn't work on table owner (PostgreSQL limitation)
    # - For production: Implement separate owner user (see roadmap)
    # - For development: Document that TRUNCATE should only be used by DBA for testing
    op.execute(
        """
        CREATE RULE audit_logs_no_update AS
            ON UPDATE TO audit_logs
            DO INSTEAD NOTHING;
        """
    )
    op.execute(
        """
        CREATE RULE audit_logs_no_delete AS
            ON DELETE TO audit_logs
            DO INSTEAD NOTHING;
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Drop immutability RULES first (before dropping table)
    op.execute("DROP RULE IF EXISTS audit_logs_no_delete ON audit_logs;")
    op.execute("DROP RULE IF EXISTS audit_logs_no_update ON audit_logs;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_index("idx_audit_user_action", table_name="audit_logs")
    op.drop_index("idx_audit_resource", table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
