"""add sessions table and refresh_tokens FK

Revision ID: 523a1b3b5c03
Revises: f989dbc0c129
Create Date: 2025-11-26 03:07:45.341179+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "523a1b3b5c03"
down_revision: Union[str, Sequence[str], None] = "f989dbc0c129"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column(
            "user_id", sa.Uuid(), nullable=False, comment="User who owns this session"
        ),
        sa.Column(
            "device_info",
            sa.String(length=255),
            nullable=True,
            comment="Parsed device info (browser, OS)",
        ),
        sa.Column(
            "user_agent",
            sa.Text(),
            nullable=True,
            comment="Full user agent string from HTTP header",
        ),
        sa.Column(
            "ip_address",
            postgresql.INET(),
            nullable=True,
            comment="Client IP address at session creation",
        ),
        sa.Column(
            "location",
            sa.String(length=255),
            nullable=True,
            comment="Geographic location from IP geolocation",
        ),
        sa.Column(
            "last_activity_at",
            sa.DateTime(),
            nullable=True,
            comment="Timestamp of last user activity in this session",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(),
            nullable=True,
            comment="When session expires (matches refresh token lifetime)",
        ),
        sa.Column(
            "is_revoked",
            sa.Boolean(),
            nullable=False,
            comment="Whether session has been revoked",
        ),
        sa.Column(
            "is_trusted",
            sa.Boolean(),
            nullable=False,
            comment="Whether this device is trusted",
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(),
            nullable=True,
            comment="Timestamp when session was revoked",
        ),
        sa.Column(
            "revoked_reason",
            sa.String(length=255),
            nullable=True,
            comment="Reason for revocation (logout, password_change, theft, etc.)",
        ),
        sa.Column(
            "refresh_token_id",
            sa.Uuid(),
            nullable=True,
            comment="Associated refresh token ID (for reference)",
        ),
        sa.Column(
            "last_ip_address",
            postgresql.INET(),
            nullable=True,
            comment="Most recent client IP (for detecting IP changes)",
        ),
        sa.Column(
            "suspicious_activity_count",
            sa.Integer(),
            nullable=False,
            comment="Counter for suspicious activity events",
        ),
        sa.Column(
            "last_provider_accessed",
            sa.String(length=100),
            nullable=True,
            comment="Last financial provider accessed in this session",
        ),
        sa.Column(
            "last_provider_sync_at",
            sa.DateTime(),
            nullable=True,
            comment="Timestamp of last provider sync in this session",
        ),
        sa.Column(
            "providers_accessed",
            postgresql.ARRAY(sa.String(length=100)),
            nullable=True,
            comment="List of providers accessed in this session",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_sessions_cleanup", "sessions", ["expires_at", "is_revoked"], unique=False
    )
    op.create_index(
        "idx_sessions_user_active",
        "sessions",
        ["user_id", "is_revoked", "expires_at"],
        unique=False,
        postgresql_where="is_revoked = false",
    )
    op.create_index(
        op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_sessions_is_revoked"), "sessions", ["is_revoked"], unique=False
    )
    op.create_index(
        op.f("ix_sessions_refresh_token_id"),
        "sessions",
        ["refresh_token_id"],
        unique=False,
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.alter_column(
        "refresh_tokens",
        "session_id",
        existing_type=sa.UUID(),
        comment="Session this token belongs to",
        existing_comment="Session this token belongs to (FK constraint added in F1.3)",
        existing_nullable=False,
    )
    op.create_foreign_key(
        "fk_refresh_tokens_session_id", "refresh_tokens", "sessions", ["session_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_refresh_tokens_session_id", "refresh_tokens", type_="foreignkey")
    op.alter_column(
        "refresh_tokens",
        "session_id",
        existing_type=sa.UUID(),
        comment="Session this token belongs to (FK constraint added in F1.3)",
        existing_comment="Session this token belongs to",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_refresh_token_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_is_revoked"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_index(
        "idx_sessions_user_active",
        table_name="sessions",
        postgresql_where="is_revoked = false",
    )
    op.drop_index("idx_sessions_cleanup", table_name="sessions")
    op.drop_table("sessions")
    # ### end Alembic commands ###
