"""add_fk_provider_connections_provider_id

Revision ID: 351384faf4aa
Revises: 24e0820ac347
Create Date: 2025-12-03 05:38:04.458991+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "351384faf4aa"
down_revision: Union[str, Sequence[str], None] = "24e0820ac347"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "provider_connections",
        "provider_id",
        existing_type=sa.UUID(),
        comment="Provider UUID (FK to providers table)",
        existing_comment="Provider UUID (FK to providers table in future)",
        existing_nullable=False,
    )
    op.create_foreign_key(
        None, "provider_connections", "providers", ["provider_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "provider_connections", type_="foreignkey")
    op.alter_column(
        "provider_connections",
        "provider_id",
        existing_type=sa.UUID(),
        comment="Provider UUID (FK to providers table in future)",
        existing_comment="Provider UUID (FK to providers table)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
