"""make audit_logs context field nullable

Fixes protocol violation where AuditProtocol.record() allows context=None
but database schema required NOT NULL. This change aligns database schema
with protocol contract to satisfy Liskov Substitution Principle.

Semantic difference:
- None = "no context provided" (system didn't capture context)
- {} = "context provided but empty" (system captured context, but it's empty)

Revision ID: 74d01428951a
Revises: b7a1d68f632a
Create Date: 2025-11-16 20:52:40.567004+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "74d01428951a"
down_revision: Union[str, Sequence[str], None] = "b7a1d68f632a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_logs",
        "context",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
        existing_comment="Additional event context (JSONB - extensible without schema changes)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_logs",
        "context",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
        existing_comment="Additional event context (JSONB - extensible without schema changes)",
    )
    # ### end Alembic commands ###
