"""add_token_breach_rotation_fields

Revision ID: a6af49534f78
Revises: b46d4a9c9dd8
Create Date: 2025-11-27 01:48:41.043479+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6af49534f78"
down_revision: Union[str, Sequence[str], None] = "b46d4a9c9dd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "security_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "global_min_token_version",
            sa.Integer(),
            nullable=False,
            comment="Minimum acceptable token version globally (increment on breach)",
        ),
        sa.Column(
            "grace_period_seconds",
            sa.Integer(),
            nullable=False,
            comment="Seconds to allow old tokens after rotation (gradual rollout)",
        ),
        sa.Column(
            "last_rotation_at",
            sa.DateTime(),
            nullable=True,
            comment="Timestamp when global rotation was last triggered",
        ),
        sa.Column(
            "last_rotation_reason",
            sa.Text(),
            nullable=True,
            comment="Reason for last global rotation (breach, vulnerability, etc.)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("id = 1", name="single_row_constraint"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "token_version",
            sa.Integer(),
            nullable=False,
            server_default="1",
            comment="Token version at issuance (must be >= required minimum)",
        ),
    )
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "global_version_at_issuance",
            sa.Integer(),
            nullable=False,
            server_default="1",
            comment="Global min version when token was issued (for grace period)",
        ),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_version"),
        "refresh_tokens",
        ["token_version"],
        unique=False,
    )
    op.add_column(
        "users",
        sa.Column(
            "min_token_version",
            sa.Integer(),
            nullable=False,
            server_default="1",
            comment="Per-user minimum token version (increment on password change, security event)",
        ),
    )
    op.create_index(
        op.f("ix_users_min_token_version"), "users", ["min_token_version"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_min_token_version"), table_name="users")
    op.drop_column("users", "min_token_version")
    op.drop_index(op.f("ix_refresh_tokens_token_version"), table_name="refresh_tokens")
    op.drop_column("refresh_tokens", "global_version_at_issuance")
    op.drop_column("refresh_tokens", "token_version")
    op.drop_table("security_config")
    # ### end Alembic commands ###
