"""add authentication tables

Revision ID: 4eaa719c463d
Revises: 74d01428951a
Create Date: 2025-11-22 20:43:26.213634+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4eaa719c463d"
down_revision: Union[str, Sequence[str], None] = "74d01428951a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
            comment="User email address (unique, lowercase)",
        ),
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=False,
            comment="Bcrypt hashed password (cost factor 12)",
        ),
        sa.Column(
            "is_verified",
            sa.Boolean(),
            nullable=False,
            comment="Email verification status (must be True to login)",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Account active status (deactivated users cannot login)",
        ),
        sa.Column(
            "failed_login_attempts",
            sa.Integer(),
            nullable=False,
            comment="Counter for failed login attempts (resets on success)",
        ),
        sa.Column(
            "locked_until",
            sa.DateTime(),
            nullable=True,
            comment="Timestamp until which account is locked (15 min after 5 failures)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_is_verified"), "users", ["is_verified"], unique=False
    )
    op.create_table(
        "email_verification_tokens",
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="User who needs to verify their email",
        ),
        sa.Column(
            "token",
            sa.String(length=64),
            nullable=False,
            comment="Random verification token (64-char hex string)",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(),
            nullable=False,
            comment="Timestamp when token expires (24 hours from creation)",
        ),
        sa.Column(
            "used_at",
            sa.DateTime(),
            nullable=True,
            comment="Timestamp when token was used (one-time use)",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_email_verification_cleanup",
        "email_verification_tokens",
        ["expires_at", "used_at"],
        unique=False,
        postgresql_where="used_at IS NULL",
    )
    op.create_index(
        op.f("ix_email_verification_tokens_expires_at"),
        "email_verification_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_tokens_token"),
        "email_verification_tokens",
        ["token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_email_verification_tokens_user_id"),
        "email_verification_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="User who requested password reset",
        ),
        sa.Column(
            "token",
            sa.String(length=64),
            nullable=False,
            comment="Random password reset token (64-char hex string)",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(),
            nullable=False,
            comment="Timestamp when token expires (15 minutes from creation)",
        ),
        sa.Column(
            "used_at",
            sa.DateTime(),
            nullable=True,
            comment="Timestamp when token was used (one-time use)",
        ),
        sa.Column(
            "ip_address",
            postgresql.INET(),
            nullable=True,
            comment="IP address of requester (security tracking)",
        ),
        sa.Column(
            "user_agent",
            sa.Text(),
            nullable=True,
            comment="User agent of requester (security tracking)",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_password_reset_cleanup",
        "password_reset_tokens",
        ["expires_at", "used_at"],
        unique=False,
        postgresql_where="used_at IS NULL",
    )
    op.create_index(
        op.f("ix_password_reset_tokens_expires_at"),
        "password_reset_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_token"),
        "password_reset_tokens",
        ["token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"),
        "password_reset_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="User who owns this refresh token",
        ),
        sa.Column(
            "token_hash",
            sa.String(length=255),
            nullable=False,
            comment="Bcrypt hashed refresh token (NEVER plaintext)",
        ),
        sa.Column(
            "session_id",
            sa.Uuid(),
            nullable=False,
            comment="Session this token belongs to (FK constraint added in F1.3)",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(),
            nullable=False,
            comment="Timestamp when token expires (30 days from creation)",
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(),
            nullable=True,
            comment="Timestamp when token was revoked (nullable)",
        ),
        sa.Column(
            "revoked_reason",
            sa.Text(),
            nullable=True,
            comment="Reason for revocation (logout, password_change, theft_detected)",
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(),
            nullable=True,
            comment="Timestamp when token was last used (for monitoring)",
        ),
        sa.Column(
            "rotation_count",
            sa.Integer(),
            nullable=False,
            comment="Number of times token has been rotated (security monitoring)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_refresh_tokens_cleanup",
        "refresh_tokens",
        ["expires_at", "revoked_at"],
        unique=False,
        postgresql_where="revoked_at IS NULL",
    )
    op.create_index(
        op.f("ix_refresh_tokens_expires_at"),
        "refresh_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_session_id"),
        "refresh_tokens",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_session_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens")
    op.drop_index(
        "idx_refresh_tokens_cleanup",
        table_name="refresh_tokens",
        postgresql_where="revoked_at IS NULL",
    )
    op.drop_table("refresh_tokens")
    op.drop_index(
        op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens"
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_token"), table_name="password_reset_tokens"
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_expires_at"), table_name="password_reset_tokens"
    )
    op.drop_index(
        "idx_password_reset_cleanup",
        table_name="password_reset_tokens",
        postgresql_where="used_at IS NULL",
    )
    op.drop_table("password_reset_tokens")
    op.drop_index(
        op.f("ix_email_verification_tokens_user_id"),
        table_name="email_verification_tokens",
    )
    op.drop_index(
        op.f("ix_email_verification_tokens_token"),
        table_name="email_verification_tokens",
    )
    op.drop_index(
        op.f("ix_email_verification_tokens_expires_at"),
        table_name="email_verification_tokens",
    )
    op.drop_index(
        "idx_email_verification_cleanup",
        table_name="email_verification_tokens",
        postgresql_where="used_at IS NULL",
    )
    op.drop_table("email_verification_tokens")
    op.drop_index(op.f("ix_users_is_verified"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
