"""add session management fields to users table

Revision ID: f989dbc0c129
Revises: 4eaa719c463d
Create Date: 2025-11-26 02:56:31.121179+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f989dbc0c129"
down_revision: Union[str, Sequence[str], None] = "4eaa719c463d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "session_tier",
            sa.String(length=50),
            nullable=False,
            server_default="basic",
            comment="Session tier (basic, essential, plus, premium, pro)",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "max_sessions",
            sa.Integer(),
            nullable=True,
            comment="Admin override for max sessions (null = use tier default)",
        ),
    )
    op.create_index(
        op.f("ix_users_session_tier"), "users", ["session_tier"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_session_tier"), table_name="users")
    op.drop_column("users", "max_sessions")
    op.drop_column("users", "session_tier")
    # ### end Alembic commands ###
