"""add_category_column_to_providers

Revision ID: e653302c726d
Revises: 351384faf4aa
Create Date: 2025-12-26 01:28:09.779292+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e653302c726d"
down_revision: Union[str, Sequence[str], None] = "351384faf4aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server_default for existing rows
    op.add_column(
        "providers",
        sa.Column(
            "category",
            sa.String(length=20),
            nullable=False,
            server_default="other",
            comment="Provider category: brokerage, bank, credit_card, loan, crypto, aggregator, other",
        ),
    )
    op.create_index(
        op.f("ix_providers_category"), "providers", ["category"], unique=False
    )

    # Update Schwab to correct category (seeded as brokerage)
    op.execute("UPDATE providers SET category = 'brokerage' WHERE slug = 'schwab'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_providers_category"), table_name="providers")
    op.drop_column("providers", "category")
    # ### end Alembic commands ###
