"""fix_security_config_timezone

Revision ID: f83d1b1ef7e2
Revises: a6af49534f78
Create Date: 2025-11-27 03:06:41.002981+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f83d1b1ef7e2"
down_revision: Union[str, Sequence[str], None] = "a6af49534f78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "security_config",
        "last_rotation_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Timestamp when global rotation was last triggered",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "security_config",
        "last_rotation_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_comment="Timestamp when global rotation was last triggered",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
