"""Add Session model and link RefreshToken to Session

Revision ID: 1a87a97a6d84
Revises: 4a6cbff7f68b
Create Date: 2025-11-03 03:43:34.646350+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1a87a97a6d84"
down_revision: Union[str, Sequence[str], None] = "4a6cbff7f68b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("event_details", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_session_audit_event_type",
        "session_audit_logs",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_audit_logs_event_type"),
        "session_audit_logs",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_audit_logs_id"), "session_audit_logs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_session_audit_logs_session_id"),
        "session_audit_logs",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_audit_logs_user_id"),
        "session_audit_logs",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_session_audit_session_created",
        "session_audit_logs",
        ["session_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_session_audit_user_created",
        "session_audit_logs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_info", sa.Text(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_activity", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_revoked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_trusted", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=True),
        sa.Column(
            "is_trusted_device", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sessions_fingerprint"), "sessions", ["fingerprint"], unique=False
    )
    op.create_index(op.f("ix_sessions_id"), "sessions", ["id"], unique=False)
    op.create_index(
        op.f("ix_sessions_is_revoked"), "sessions", ["is_revoked"], unique=False
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.add_column("refresh_tokens", sa.Column("session_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_refresh_tokens_session_id"),
        "refresh_tokens",
        ["session_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "refresh_tokens", "sessions", ["session_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###

    # Manual data migration: Create sessions from existing refresh tokens
    connection = op.get_bind()
    result = connection.execute(
        sa.text(
            """
            INSERT INTO sessions (
                id, user_id, device_info, ip_address, user_agent, location,
                created_at, last_activity, expires_at, is_revoked, is_trusted,
                revoked_at, revoked_reason, updated_at, deleted_at, is_active,
                fingerprint, is_trusted_device
            )
            SELECT
                gen_random_uuid(),
                user_id,
                device_info,
                ip_address,
                user_agent,
                location,
                created_at,
                last_used_at,
                expires_at,
                is_revoked,
                is_trusted_device,  -- Copy to is_trusted
                revoked_at,
                NULL,  -- revoked_reason - not in refresh_tokens
                updated_at,
                deleted_at,
                is_active,
                fingerprint,
                is_trusted_device
            FROM refresh_tokens
            RETURNING id, user_id, created_at
            """
        )
    )
    # Store the session IDs for updating refresh_tokens
    sessions = result.fetchall()

    # Update refresh_tokens to point to the new sessions
    # Match by user_id and created_at to link tokens to their sessions
    for session_id, user_id, created_at in sessions:
        connection.execute(
            sa.text(
                """
                UPDATE refresh_tokens
                SET session_id = :session_id
                WHERE user_id = :user_id
                  AND created_at = :created_at
                  AND session_id IS NULL
                """
            ),
            {"session_id": session_id, "user_id": user_id, "created_at": created_at},
        )

    # Now drop the redundant columns from refresh_tokens
    op.drop_column("refresh_tokens", "device_info")
    op.drop_column("refresh_tokens", "ip_address")
    op.drop_column("refresh_tokens", "user_agent")
    op.drop_column("refresh_tokens", "location")
    op.drop_column("refresh_tokens", "last_used_at")
    op.drop_column("refresh_tokens", "fingerprint")
    op.drop_column("refresh_tokens", "is_trusted_device")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, restore the columns that were removed from refresh_tokens
    op.add_column(
        "refresh_tokens",
        sa.Column("device_info", sa.Text(), nullable=True),
    )
    op.add_column(
        "refresh_tokens",
        sa.Column("ip_address", postgresql.INET(), nullable=True),
    )
    op.add_column(
        "refresh_tokens",
        sa.Column("user_agent", sa.Text(), nullable=True),
    )
    op.add_column(
        "refresh_tokens",
        sa.Column("location", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "refresh_tokens",
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "refresh_tokens",
        sa.Column("fingerprint", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "is_trusted_device", sa.Boolean(), server_default="false", nullable=False
        ),
    )

    # Copy data back from sessions to refresh_tokens
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
            UPDATE refresh_tokens rt
            SET
                device_info = s.device_info,
                ip_address = s.ip_address,
                user_agent = s.user_agent,
                location = s.location,
                last_used_at = s.last_activity,
                fingerprint = s.fingerprint,
                is_trusted_device = s.is_trusted_device
            FROM sessions s
            WHERE rt.session_id = s.id
            """
        )
    )

    # Now drop the foreign key and session_id column
    op.drop_constraint(None, "refresh_tokens", type_="foreignkey")
    op.drop_index(op.f("ix_refresh_tokens_session_id"), table_name="refresh_tokens")
    op.drop_column("refresh_tokens", "session_id")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_is_revoked"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_fingerprint"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("ix_session_audit_user_created", table_name="session_audit_logs")
    op.drop_index("ix_session_audit_session_created", table_name="session_audit_logs")
    op.drop_index(
        op.f("ix_session_audit_logs_user_id"), table_name="session_audit_logs"
    )
    op.drop_index(
        op.f("ix_session_audit_logs_session_id"), table_name="session_audit_logs"
    )
    op.drop_index(op.f("ix_session_audit_logs_id"), table_name="session_audit_logs")
    op.drop_index(
        op.f("ix_session_audit_logs_event_type"), table_name="session_audit_logs"
    )
    op.drop_index("ix_session_audit_event_type", table_name="session_audit_logs")
    op.drop_table("session_audit_logs")
    # ### end Alembic commands ###
