"""add_session_management_fields

Revision ID: a5270ef91c56
Revises: 92fe57a303d8
Create Date: 2025-10-28 16:45:05.751809+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5270ef91c56"
down_revision: Union[str, Sequence[str], None] = "92fe57a303d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_tokens", sa.Column("location", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "refresh_tokens", sa.Column("fingerprint", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "is_trusted_device", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.create_index(
        op.f("ix_refresh_tokens_fingerprint"),
        "refresh_tokens",
        ["fingerprint"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_tokens_fingerprint"), table_name="refresh_tokens")
    op.drop_column("refresh_tokens", "is_trusted_device")
    op.drop_column("refresh_tokens", "fingerprint")
    op.drop_column("refresh_tokens", "location")
    # ### end Alembic commands ###
