"""add_accounts_table

Revision ID: 641ca1055f55
Revises: 15dca8efc4fd
Create Date: 2025-12-01 04:50:02.068480+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "641ca1055f55"
down_revision: Union[str, Sequence[str], None] = "15dca8efc4fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column(
            "connection_id",
            sa.Uuid(),
            nullable=False,
            comment="FK to provider_connections table",
        ),
        sa.Column(
            "provider_account_id",
            sa.String(length=100),
            nullable=False,
            comment="Provider's unique account identifier",
        ),
        sa.Column(
            "account_number_masked",
            sa.String(length=50),
            nullable=False,
            comment="Masked account number (****1234)",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Account name from provider",
        ),
        sa.Column(
            "account_type",
            sa.String(length=50),
            nullable=False,
            comment="Account type (brokerage, checking, ira, etc.)",
        ),
        sa.Column(
            "balance",
            sa.Numeric(precision=19, scale=4),
            nullable=False,
            comment="Current balance amount",
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=False,
            comment="ISO 4217 currency code",
        ),
        sa.Column(
            "available_balance",
            sa.Numeric(precision=19, scale=4),
            nullable=True,
            comment="Available balance (if different from balance)",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether account is active on provider",
        ),
        sa.Column(
            "last_synced_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Last successful sync timestamp",
        ),
        sa.Column(
            "provider_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Provider-specific data (unstructured)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"], ["provider_connections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "connection_id",
            "provider_account_id",
            name="uq_accounts_connection_provider",
        ),
    )
    op.create_index(
        "idx_accounts_active",
        "accounts",
        ["connection_id"],
        unique=False,
        postgresql_where="is_active = true",
    )
    op.create_index(
        op.f("ix_accounts_account_type"), "accounts", ["account_type"], unique=False
    )
    op.create_index(
        op.f("ix_accounts_connection_id"), "accounts", ["connection_id"], unique=False
    )
    op.create_index(
        op.f("ix_accounts_is_active"), "accounts", ["is_active"], unique=False
    )
    op.alter_column(
        "provider_connections",
        "encrypted_credentials",
        existing_type=postgresql.BYTEA(),
        comment="AES-256 encrypted credential blob (domain sees ProviderCredentials)",
        existing_comment="AES-256 encrypted credential blob",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "provider_connections",
        "encrypted_credentials",
        existing_type=postgresql.BYTEA(),
        comment="AES-256 encrypted credential blob",
        existing_comment="AES-256 encrypted credential blob (domain sees ProviderCredentials)",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_accounts_is_active"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_connection_id"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_account_type"), table_name="accounts")
    op.drop_index(
        "idx_accounts_active",
        table_name="accounts",
        postgresql_where="is_active = true",
    )
    op.drop_table("accounts")
    # ### end Alembic commands ###
