"""add_casbin_rule_v3_v5_columns

Revision ID: 421e9f50970f
Revises: f799ad043ec5
Create Date: 2025-11-27 07:13:56.969841+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "421e9f50970f"
down_revision: Union[str, Sequence[str], None] = "f799ad043ec5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "casbin_rule",
        sa.Column(
            "v3",
            sa.String(length=255),
            nullable=True,
            comment="Policy value 3 (reserved for domains/ABAC)",
        ),
    )
    op.add_column(
        "casbin_rule",
        sa.Column(
            "v4",
            sa.String(length=255),
            nullable=True,
            comment="Policy value 4 (reserved for domains/ABAC)",
        ),
    )
    op.add_column(
        "casbin_rule",
        sa.Column(
            "v5",
            sa.String(length=255),
            nullable=True,
            comment="Policy value 5 (reserved for domains/ABAC)",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("casbin_rule", "v5")
    op.drop_column("casbin_rule", "v4")
    op.drop_column("casbin_rule", "v3")
    # ### end Alembic commands ###
