"""add_balance_snapshots_table

Revision ID: b568ab23752a
Revises: cc2348960654
Create Date: 2025-12-26 02:34:46.478193+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b568ab23752a"
down_revision: Union[str, Sequence[str], None] = "cc2348960654"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "balance_snapshots",
        sa.Column(
            "account_id", sa.Uuid(), nullable=False, comment="FK to accounts table"
        ),
        sa.Column(
            "balance_amount",
            sa.Numeric(precision=19, scale=4),
            nullable=False,
            comment="Total account balance at capture time",
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=False,
            comment="ISO 4217 currency code",
        ),
        sa.Column(
            "available_balance_amount",
            sa.Numeric(precision=19, scale=4),
            nullable=True,
            comment="Available balance (if different from total)",
        ),
        sa.Column(
            "holdings_value_amount",
            sa.Numeric(precision=19, scale=4),
            nullable=True,
            comment="Total market value of holdings/positions",
        ),
        sa.Column(
            "cash_value_amount",
            sa.Numeric(precision=19, scale=4),
            nullable=True,
            comment="Cash/money market balance",
        ),
        sa.Column(
            "source",
            sa.String(length=50),
            nullable=False,
            comment="How/why snapshot was captured (account_sync, manual_sync, etc.)",
        ),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when balance was captured",
        ),
        sa.Column(
            "provider_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Provider-specific data at capture time",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_balance_snapshots_account_source_time",
        "balance_snapshots",
        ["account_id", "source", "captured_at"],
        unique=False,
    )
    op.create_index(
        "idx_balance_snapshots_account_time",
        "balance_snapshots",
        ["account_id", "captured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_balance_snapshots_account_id"),
        "balance_snapshots",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_balance_snapshots_captured_at"),
        "balance_snapshots",
        ["captured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_balance_snapshots_source"),
        "balance_snapshots",
        ["source"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_balance_snapshots_source"), table_name="balance_snapshots")
    op.drop_index(
        op.f("ix_balance_snapshots_captured_at"), table_name="balance_snapshots"
    )
    op.drop_index(
        op.f("ix_balance_snapshots_account_id"), table_name="balance_snapshots"
    )
    op.drop_index("idx_balance_snapshots_account_time", table_name="balance_snapshots")
    op.drop_index(
        "idx_balance_snapshots_account_source_time", table_name="balance_snapshots"
    )
    op.drop_table("balance_snapshots")
    # ### end Alembic commands ###
