"""add_providers_table

Revision ID: 24e0820ac347
Revises: 8a71627a669d
Create Date: 2025-12-03 05:31:03.423626+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24e0820ac347"
down_revision: Union[str, Sequence[str], None] = "8a71627a669d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providers",
        sa.Column(
            "slug",
            sa.String(length=50),
            nullable=False,
            comment="URL-safe unique identifier (e.g., 'schwab')",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Human-readable name (e.g., 'Charles Schwab')",
        ),
        sa.Column(
            "credential_type",
            sa.String(length=20),
            nullable=False,
            comment="Credential type: oauth2, api_key, link_token, certificate, custom",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Optional description for UI display",
        ),
        sa.Column(
            "logo_url",
            sa.String(length=500),
            nullable=True,
            comment="Optional URL to provider logo",
        ),
        sa.Column(
            "website_url",
            sa.String(length=500),
            nullable=True,
            comment="Optional provider website URL",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether provider is available for new connections",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_providers_active_slug",
        "providers",
        ["is_active", "slug"],
        unique=False,
        postgresql_where="is_active = true",
    )
    op.create_index(
        op.f("ix_providers_is_active"), "providers", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_providers_slug"), "providers", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_providers_slug"), table_name="providers")
    op.drop_index(op.f("ix_providers_is_active"), table_name="providers")
    op.drop_index(
        "idx_providers_active_slug",
        table_name="providers",
        postgresql_where="is_active = true",
    )
    op.drop_table("providers")
    # ### end Alembic commands ###
