"""add_token_versioning_hybrid_approach

Revision ID: 4a6cbff7f68b
Revises: a5270ef91c56
Create Date: 2025-10-29 23:10:04.980506+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a6cbff7f68b"
down_revision: Union[str, Sequence[str], None] = "a5270ef91c56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "security_config",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("global_min_token_version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_security_config_id"), "security_config", ["id"], unique=False
    )
    # Insert initial security_config row (singleton)
    op.execute(
        """
        INSERT INTO security_config (id, global_min_token_version, updated_at, created_at, is_active)
        VALUES (gen_random_uuid(), 1, NOW(), NOW(), true)
        """
    )
    op.add_column(
        "refresh_tokens",
        sa.Column("token_version", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "global_version_at_issuance",
            sa.Integer(),
            server_default="1",
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_refresh_tokens_global_version_at_issuance"),
        "refresh_tokens",
        ["global_version_at_issuance"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_version"),
        "refresh_tokens",
        ["token_version"],
        unique=False,
    )
    op.add_column(
        "users",
        sa.Column(
            "min_token_version", sa.Integer(), server_default="1", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "min_token_version")
    op.drop_index(op.f("ix_refresh_tokens_token_version"), table_name="refresh_tokens")
    op.drop_index(
        op.f("ix_refresh_tokens_global_version_at_issuance"),
        table_name="refresh_tokens",
    )
    op.drop_column("refresh_tokens", "global_version_at_issuance")
    op.drop_column("refresh_tokens", "token_version")
    op.drop_index(op.f("ix_security_config_id"), table_name="security_config")
    op.drop_table("security_config")
    # ### end Alembic commands ###
