"""Add rate_limit_audit_logs with INET and identifier

Revision ID: 92fe57a303d8
Revises: e18e20278eaa
Create Date: 2025-10-26 16:52:00.727846+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "92fe57a303d8"
down_revision: Union[str, Sequence[str], None] = "e18e20278eaa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limit_audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("rule_name", sa.String(length=100), nullable=False),
        sa.Column("limit", sa.Integer(), nullable=False),
        sa.Column("window_seconds", sa.Integer(), nullable=False),
        sa.Column("violation_count", sa.Integer(), nullable=False),
        sa.Column("identifier", sa.String(length=255), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rate_limit_audit_logs_endpoint"),
        "rate_limit_audit_logs",
        ["endpoint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rate_limit_audit_logs_id"),
        "rate_limit_audit_logs",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rate_limit_audit_logs_identifier"),
        "rate_limit_audit_logs",
        ["identifier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rate_limit_audit_logs_ip_address"),
        "rate_limit_audit_logs",
        ["ip_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rate_limit_audit_logs_timestamp"),
        "rate_limit_audit_logs",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_rate_limit_audit_logs_timestamp"), table_name="rate_limit_audit_logs"
    )
    op.drop_index(
        op.f("ix_rate_limit_audit_logs_ip_address"), table_name="rate_limit_audit_logs"
    )
    op.drop_index(
        op.f("ix_rate_limit_audit_logs_identifier"), table_name="rate_limit_audit_logs"
    )
    op.drop_index(
        op.f("ix_rate_limit_audit_logs_id"), table_name="rate_limit_audit_logs"
    )
    op.drop_index(
        op.f("ix_rate_limit_audit_logs_endpoint"), table_name="rate_limit_audit_logs"
    )
    op.drop_table("rate_limit_audit_logs")
    # ### end Alembic commands ###
