"""add_holdings_table

Revision ID: cc2348960654
Revises: e653302c726d
Create Date: 2025-12-26 01:56:40.708541+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cc2348960654"
down_revision: Union[str, Sequence[str], None] = "e653302c726d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holdings",
        sa.Column(
            "account_id", sa.Uuid(), nullable=False, comment="FK to accounts table"
        ),
        sa.Column(
            "provider_holding_id",
            sa.String(length=255),
            nullable=False,
            comment="Provider's unique identifier for this position",
        ),
        sa.Column(
            "symbol",
            sa.String(length=50),
            nullable=False,
            comment="Security ticker symbol (AAPL, TSLA, etc.)",
        ),
        sa.Column(
            "security_name",
            sa.String(length=255),
            nullable=False,
            comment="Full security name (Apple Inc., etc.)",
        ),
        sa.Column(
            "asset_type",
            sa.String(length=50),
            nullable=False,
            comment="Asset type (equity, etf, option, etc.)",
        ),
        sa.Column(
            "quantity",
            sa.Numeric(precision=19, scale=8),
            nullable=False,
            comment="Number of shares/units held",
        ),
        sa.Column(
            "cost_basis_amount",
            sa.Numeric(precision=19, scale=4),
            nullable=False,
            comment="Total cost paid for this position",
        ),
        sa.Column(
            "market_value_amount",
            sa.Numeric(precision=19, scale=4),
            nullable=False,
            comment="Current market value of the position",
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=False,
            comment="ISO 4217 currency code",
        ),
        sa.Column(
            "average_price_amount",
            sa.Numeric(precision=19, scale=4),
            nullable=True,
            comment="Average price per share (cost_basis / quantity)",
        ),
        sa.Column(
            "current_price_amount",
            sa.Numeric(precision=19, scale=4),
            nullable=True,
            comment="Current market price per share",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether position is still held (quantity > 0)",
        ),
        sa.Column(
            "last_synced_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Last successful sync timestamp",
        ),
        sa.Column(
            "provider_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Provider-specific data (unstructured)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id", "provider_holding_id", name="uq_holdings_account_provider"
        ),
    )
    op.create_index(
        "idx_holdings_account_symbol",
        "holdings",
        ["account_id", "symbol"],
        unique=False,
    )
    op.create_index(
        "idx_holdings_active",
        "holdings",
        ["account_id"],
        unique=False,
        postgresql_where="is_active = true",
    )
    op.create_index(
        op.f("ix_holdings_account_id"), "holdings", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_holdings_asset_type"), "holdings", ["asset_type"], unique=False
    )
    op.create_index(
        op.f("ix_holdings_is_active"), "holdings", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_holdings_symbol"), "holdings", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_holdings_symbol"), table_name="holdings")
    op.drop_index(op.f("ix_holdings_is_active"), table_name="holdings")
    op.drop_index(op.f("ix_holdings_asset_type"), table_name="holdings")
    op.drop_index(op.f("ix_holdings_account_id"), table_name="holdings")
    op.drop_index(
        "idx_holdings_active",
        table_name="holdings",
        postgresql_where="is_active = true",
    )
    op.drop_index("idx_holdings_account_symbol", table_name="holdings")
    op.drop_table("holdings")
    # ### end Alembic commands ###
