"""add casbin_rule table for RBAC

Revision ID: f799ad043ec5
Revises: f83d1b1ef7e2
Create Date: 2025-11-27 06:30:56.737305+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f799ad043ec5"
down_revision: Union[str, Sequence[str], None] = "f83d1b1ef7e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casbin_rule",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "ptype",
            sa.String(length=255),
            nullable=True,
            comment="Policy type: 'p' (permission) or 'g' (role grouping)",
        ),
        sa.Column(
            "v0",
            sa.String(length=255),
            nullable=True,
            comment="Policy value 0 (role for 'p', child for 'g')",
        ),
        sa.Column(
            "v1",
            sa.String(length=255),
            nullable=True,
            comment="Policy value 1 (resource for 'p', parent for 'g')",
        ),
        sa.Column(
            "v2",
            sa.String(length=255),
            nullable=True,
            comment="Policy value 2 (action for 'p', unused for 'g')",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_casbin_rule_ptype", "casbin_rule", ["ptype"], unique=False)
    op.create_index("idx_casbin_rule_v0", "casbin_rule", ["v0"], unique=False)
    op.create_index(
        "idx_casbin_rule_v0_v1_v2", "casbin_rule", ["v0", "v1", "v2"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_casbin_rule_v0_v1_v2", table_name="casbin_rule")
    op.drop_index("idx_casbin_rule_v0", table_name="casbin_rule")
    op.drop_index("idx_casbin_rule_ptype", table_name="casbin_rule")
    op.drop_table("casbin_rule")
    # ### end Alembic commands ###
