"""add transactions table

Revision ID: 8a71627a669d
Revises: 641ca1055f55
Create Date: 2025-12-01 05:25:01.313766+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8a71627a669d"
down_revision: Union[str, Sequence[str], None] = "641ca1055f55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column(
            "account_id", sa.Uuid(), nullable=False, comment="FK to accounts table"
        ),
        sa.Column(
            "provider_transaction_id",
            sa.String(length=255),
            nullable=False,
            comment="Provider's unique transaction identifier",
        ),
        sa.Column(
            "transaction_type",
            sa.String(length=50),
            nullable=False,
            comment="Transaction type (trade, transfer, income, fee, other)",
        ),
        sa.Column(
            "subtype",
            sa.String(length=50),
            nullable=False,
            comment="Transaction subtype (buy, sell, deposit, dividend, etc.)",
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            comment="Transaction status (pending, settled, failed, cancelled)",
        ),
        sa.Column(
            "amount",
            sa.Numeric(precision=19, scale=4),
            nullable=False,
            comment="Transaction amount (positive=credit, negative=debit)",
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=False,
            comment="ISO 4217 currency code",
        ),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=False,
            comment="Transaction description from provider",
        ),
        sa.Column(
            "asset_type",
            sa.String(length=50),
            nullable=True,
            comment="Asset type (equity, option, etf, etc.) - TRADE only",
        ),
        sa.Column(
            "symbol",
            sa.String(length=50),
            nullable=True,
            comment="Security ticker symbol (AAPL, BTC-USD, etc.)",
        ),
        sa.Column(
            "security_name",
            sa.String(length=255),
            nullable=True,
            comment="Full security name (Apple Inc., etc.)",
        ),
        sa.Column(
            "quantity",
            sa.Numeric(precision=19, scale=8),
            nullable=True,
            comment="Number of shares/units traded",
        ),
        sa.Column(
            "unit_price_amount",
            sa.Numeric(precision=19, scale=4),
            nullable=True,
            comment="Price per share/unit",
        ),
        sa.Column(
            "commission_amount",
            sa.Numeric(precision=19, scale=4),
            nullable=True,
            comment="Trading commission/fee",
        ),
        sa.Column(
            "transaction_date",
            sa.Date(),
            nullable=False,
            comment="Date transaction occurred",
        ),
        sa.Column(
            "settlement_date",
            sa.Date(),
            nullable=True,
            comment="Date funds/securities settled",
        ),
        sa.Column(
            "provider_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Provider-specific data (unstructured)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id",
            "provider_transaction_id",
            name="uq_transactions_account_provider",
        ),
    )
    op.create_index(
        "idx_transactions_account_date",
        "transactions",
        ["account_id", "transaction_date"],
        unique=False,
    )
    op.create_index(
        "idx_transactions_settled",
        "transactions",
        ["account_id", "transaction_date"],
        unique=False,
        postgresql_where="status = 'settled'",
    )
    op.create_index(
        op.f("ix_transactions_account_id"), "transactions", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_status"), "transactions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_symbol"), "transactions", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_transaction_date"),
        "transactions",
        ["transaction_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_transaction_type"),
        "transactions",
        ["transaction_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_transaction_type"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_transaction_date"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_symbol"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_status"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_account_id"), table_name="transactions")
    op.drop_index(
        "idx_transactions_settled",
        table_name="transactions",
        postgresql_where="status = 'settled'",
    )
    op.drop_index("idx_transactions_account_date", table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
